version: "3.9"

services:
    app:
        build:
            context: ./.docker
        container_name: app
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./.docker/php/jit.ini:/usr/local/etc/php/conf.d/jit.ini
            - ./.docker/php/debug.ini:/usr/local/etc/php/conf.d/debug.ini
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        ports:
            - "8000:8002"
        networks:
            - just-another-network

networks:
    just-another-network:
        driver: bridge
